name: disease
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  audioplayers: ^6.1.1
  collection: ^1.19.0
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/Whispers_of_the_Moon.mp3
    - assets/audio/Cry_For_Me.mp3
    - assets/audio/Brylie_Christopher_Oxley_-_Ethereal_Cafe.mp3
    - assets/audio/Mega_Man_(NES)_Music_-_Victory_Theme.mp3
    - assets/audio/Monplaisir_-_Defeat.mp3
    - assets/images/carta_parte_trasera.png
    - assets/images/cura_cerebro.png
    - assets/images/cura_corazon.png
    - assets/images/cura_estomago.png
    - assets/images/cura_hueso.png
    - assets/images/especial_cambio_organo.png
    - assets/images/especial_contagio.png
    - assets/images/especial_error_medico.png
    - assets/images/especial_guante_latex.png
    - assets/images/especial_robo.png
    - assets/images/organo_cerebro.png
    - assets/images/organo_corazon.png
    - assets/images/organo_estomago.png
    - assets/images/organo_hueso.png
    - assets/images/virus_cerebro.png
    - assets/images/virus_corazon.png
    - assets/images/virus_estomago.png
    - assets/images/virus_hueso.png
    - assets/images/fondo_disease.png
    - assets/images/fondoVerde.png


